"""Invitation flow: invite -> email -> preview -> accept -> membership,
plus the security rules the milestone calls out explicitly: only
ADMIN+ can invite/revoke, the accepting user must match the invited
email, tokens are single-use, and expired/revoked invites are rejected.
"""

from httpx import AsyncClient

from fastauthx_orgs.models import RoleEnum


async def _create_org(client: AsyncClient, name: str = "Acme Inc") -> dict:
    response = await client.post("/orgs", json={"name": name})
    assert response.status_code == 201
    return response.json()


async def test_admin_can_invite_a_member(
    client: AsyncClient, fake_email_sender
) -> None:
    organization = await _create_org(client)

    response = await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": "invitee@example.com", "role": "MEMBER"},
    )

    assert response.status_code == 201
    body = response.json()
    assert body["email"] == "invitee@example.com"
    assert "token" not in body and "token_hash" not in body

    sent = [e for e in fake_email_sender.sent if e.to == "invitee@example.com"]
    assert len(sent) == 1
    assert organization["name"] in sent[0].subject


async def test_member_cannot_invite(
    client: AsyncClient, current_user_holder: dict, make_user, add_member
) -> None:
    owner = current_user_holder["user"]
    organization = await _create_org(client)

    member = await make_user("Plain Member")
    await add_member(organization["id"], member.id, RoleEnum.MEMBER)
    current_user_holder["user"] = member

    response = await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": "invitee@example.com"},
    )

    assert response.status_code == 403
    current_user_holder["user"] = owner


async def test_cannot_invite_an_existing_member(
    client: AsyncClient, make_user, add_member
) -> None:
    organization = await _create_org(client)
    existing = await make_user("Already Here")
    await add_member(organization["id"], existing.id, RoleEnum.MEMBER)

    response = await client.post(
        f"/orgs/{organization['id']}/invitations", json={"email": existing.email}
    )

    assert response.status_code == 409


async def test_preview_invitation_by_token(
    client: AsyncClient, fake_email_sender
) -> None:
    organization = await _create_org(client)
    await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": "invitee@example.com", "role": "ADMIN"},
    )
    token = fake_email_sender.extract_token("invitee@example.com")

    response = await client.get(f"/invitations/{token}")

    assert response.status_code == 200
    body = response.json()
    assert body["organization_name"] == organization["name"]
    assert body["role"] == "ADMIN"
    assert body["accepted_at"] is None


async def test_preview_unknown_token_is_404(client: AsyncClient) -> None:
    response = await client.get("/invitations/not-a-real-token")
    assert response.status_code == 404


async def test_accept_invitation_creates_membership(
    client: AsyncClient,
    current_user_holder: dict,
    make_user,
    fake_email_sender,
) -> None:
    owner = current_user_holder["user"]
    organization = await _create_org(client)

    invitee = await make_user("Invitee")
    # fastauthx.models.Users.email is randomly generated by make_user; the
    # invite has to target that exact address for acceptance to match.
    await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": invitee.email, "role": "ADMIN"},
    )
    token = fake_email_sender.extract_token(invitee.email)

    current_user_holder["user"] = invitee
    response = await client.post(f"/invitations/{token}/accept")

    assert response.status_code == 200
    assert response.json()["role"] == "ADMIN"

    members = await client.get(f"/orgs/{organization['id']}/members")
    assert any(m["user_id"] == str(invitee.id) for m in members.json())
    current_user_holder["user"] = owner


async def test_accept_invitation_rejects_wrong_email(
    client: AsyncClient, current_user_holder: dict, make_user, fake_email_sender
) -> None:
    owner = current_user_holder["user"]
    organization = await _create_org(client)

    await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": "intended@example.com"},
    )
    token = fake_email_sender.extract_token("intended@example.com")

    someone_else = await make_user("Someone Else")
    current_user_holder["user"] = someone_else

    response = await client.post(f"/invitations/{token}/accept")

    assert response.status_code == 403
    current_user_holder["user"] = owner


async def test_accept_invitation_token_is_single_use(
    client: AsyncClient, current_user_holder: dict, make_user, fake_email_sender
) -> None:
    owner = current_user_holder["user"]
    organization = await _create_org(client)

    invitee = await make_user("Invitee")
    await client.post(
        f"/orgs/{organization['id']}/invitations", json={"email": invitee.email}
    )
    token = fake_email_sender.extract_token(invitee.email)

    current_user_holder["user"] = invitee
    first = await client.post(f"/invitations/{token}/accept")
    assert first.status_code == 200

    second = await client.post(f"/invitations/{token}/accept")
    assert second.status_code == 409
    current_user_holder["user"] = owner


async def test_admin_can_revoke_an_invitation(
    client: AsyncClient, fake_email_sender
) -> None:
    organization = await _create_org(client)
    create_response = await client.post(
        f"/orgs/{organization['id']}/invitations", json={"email": "invitee@example.com"}
    )
    invitation_id = create_response.json()["id"]

    revoke_response = await client.delete(
        f"/orgs/{organization['id']}/invitations/{invitation_id}"
    )
    assert revoke_response.status_code == 204

    token = fake_email_sender.extract_token("invitee@example.com")
    accept_response = await client.post(f"/invitations/{token}/accept")
    assert accept_response.status_code == 404


async def test_reinviting_replaces_the_previous_invitation(
    client: AsyncClient, fake_email_sender
) -> None:
    organization = await _create_org(client)

    await client.post(
        f"/orgs/{organization['id']}/invitations", json={"email": "invitee@example.com"}
    )
    first_token = fake_email_sender.extract_token("invitee@example.com")

    await client.post(
        f"/orgs/{organization['id']}/invitations",
        json={"email": "invitee@example.com", "role": "ADMIN"},
    )
    second_token = fake_email_sender.extract_token("invitee@example.com")

    assert first_token != second_token

    invitations = await client.get(f"/orgs/{organization['id']}/invitations")
    assert len(invitations.json()) == 1
    assert invitations.json()[0]["role"] == "ADMIN"
